algoritmo "Exercicio 5"
// Função : Faça um algoritmo que gere uma tabela com os números de 1 a 10 e mostre o seu quadrado, cubo,
//fatorial, número de divisores e uma mensagem dizendo se o número é primo ou não. A cada 20 linhas
//deve ser escrito o cabeçalho novamente:
//"Número Quadrado Cubo Fatorial Divisores Primo"
//1 1 1 1 1 Sim
//2 4 8 2 2 Sim
// Autor : Maison Galvão
// Data : 16/02/2016
// Seção de Declarações 
var

inicio
// Seção de Comandos 
fimalgoritmo
